version: "3.8"

services:
    app:
        build:
            context: .
        image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        environment:
            - APP_ENV=local
        command: php artisan serve --host=0.0.0.0 --port=8000
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
